name = "repro"
main = "src/worker.ts"
compatibility_date = "2024-12-09"
workers_dev = true
preview_urls = false
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "..."